### ISSUE TITLE
Doesn't seem to work with the lastest Chrome

### ISSUE THREAD

**Issue by falstro** [Cacodaimon/GhostText-for-Chrome#51]
I have just built a GVIm integration for ghost text, and was stoked that I managed to get it working. Only to have it fail a couple of days later :) The only thing I can think of is that chrome got updated in the meantime.

I'm getting a popup saying the connection failed, but I get no connection attempt on the "server" side.

I'm also getting the exception below when trying to use it with GMail, but it doesn't appear to be related as I get the same connection failure on other sites with no iframes (and no exception) and regardless of whether it's https or not.

Otherwise there's nothing noteworthy in the console, except for some debug output and "Got message: " with the error notification (and the echoing of the message to the console).

Is it just broken for me, or is there a general issue with the latest Chrome?

```
DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://mail.google.com" from accessing a cross-origin frame.
    at Error (native)
    at Detector.addIframes (file:///home/falstro/.config/google-chrome/Default/Extensions/godiecgffnchndlihlpaajjcplehddca/1.1.4_0/scripts/input-area.js:362:47)
    at Detector.detect (file:///home/falstro/.config/google-chrome/Default/Extensions/godiecgffnchndlihlpaajjcplehddca/1.1.4_0/scripts/input-area.js:153:22)
    at Detector.addIframes (file:///home/falstro/.config/google-chrome/Default/Extensions/godiecgffnchndlihlpaajjcplehddca/1.1.4_0/scripts/input-area.js:362:30)
    at Detector.detect (file:///home/falstro/.config/google-chrome/Default/Extensions/godiecgffnchndlihlpaajjcplehddca/1.1.4_0/scripts/input-area.js:153:22)
    at Object.GhostTextContent.selectField (file:///home/falstro/.config/google-chrome/Default/Extensions/godiecgffnchndlihlpaajjcplehddca/1.1.4_0/scripts/content.js:160:43)
    at GhostTextContent.messageHandler (file:///home/falstro/.config/google-chrome/Default/Extensions/godiecgffnchndlihlpaajjcplehddca/1.1.4_0/scripts/content.js:49:34)
    at EventImpl.dispatchToListener (extensions::event_bindings:387:22)
    at Event.publicClass.(anonymous function) [as dispatchToListener] (extensions::utils:94:26)
    at EventImpl.dispatch_ (extensions::event_bindings:371:35)
```

**Comment by falstro** [comment]
Never mind. One more thing had changed, I had to use a proxy server at work. It apparently used the proxy server for connections to localhost as well. Sorry for the noise.

**Comment by bfred-it** [comment]
Good thing you resolved! If you feel like sharing your integration please do! We can probably import it and keep it as a prototype, at the very least, if you don't mind.

**Comment by falstro** [comment]
It's here on github, the quality is less than stellar though, only put enough effort into it to have it work well for me ;) https://github.com/falstro/ghost-text-vim

**Comment by bfred-it** [comment]
I added it to the [main readme](https://github.com/Cacodaimon/GhostText-for-SublimeText/blob/master/README.md), somebody else might be interested :)

If https://github.com/Cacodaimon/GhostText-for-SublimeText/issues/62 goes through we could import it into the org and keep it as an official project
